### ISSUE TITLE
Release 3.0 meta-issue

### ISSUE THREAD

**Issue by filmor** [pythonnet/pythonnet#1860]
- [x] Fix constructor handling: #1116
    - [x] Make sure that all primitive types are handled correctly, at least `IntPtr` and `UIntPtr` are not right now, work in #1861 
    - [x] Also ensure that the non-simple constructors on `String` can be called, work in #1862
- [x] Fix doc strings:
    - [x] Fix constructor `__doc__` for (at least?) primitive types, work in #1865
    - [x] Fix pydoc getting confused by our `__file__` if `__doc__` is not defined (should be fixed with 1865 as well, only happens if `__doc__` does not exist for some type)
- [x] Documentation, work in #1863
    - [x] Generate the main reference docs
    - [x] Update README, add a simple example for .NET 6
- [x] Minor tweaks:
    - [x] Maybe ensure that the path of the `runtimeconfig.json` is automatically added to `sys.path`? Decided against this, as `runtime_config` is now an optional parameter.
    - [x] Maybe default to .NET Core if Mono is not available on Unix? Decided against this, it would be a much worse experience if the default changed just because someone installed Mono.
    - [x] Communicate errors in the default initialisation clearly (see #1868)
    - [x] Retrieve information about the currently loaded CLR from `clr-loader` (see https://github.com/pythonnet/clr-loader/issues/28)
- [x] Make a decision and implement reg. #1833 
- [x] Publish:
    - [x] Publish to Pypi and nuget.org
    - [x] Write release mail to the mailing list and the discussion forum
    - [x] Update the homepage accordingly (using the new Sphinx docs)
- [x] Post-release:
    - [x] Merge `release` branch back into `master`
    - [x] Adjust `docs` workflow to publish from `master` instead of `release`
    - [x] Bump version on master to `3.1.0-dev`

**Comment by filmor** [comment]
@lostmsu From my point of view, we are done and ready to release. Basic documentation for `clr_loader` and `pythonnet` are now available on https://pythonnet.github.io/clr-loader and https://pythonnet.github.io/pythonnet respectively.

I will be of limited availability for about two weeks from the 30th onward, so it would be great if we could discuss any blockers beforehand. If there are no blockers until Wednesday, I will tag and release this version as is.

**Comment by lostmsu** [comment]
@filmor we just made a breaking change with float conversions. Not sure about Unity, but I would have to ensure it does not break anything. Probably will be able to do it until then.

**Comment by lostmsu** [comment]
Heads up: I run the full test suite we have on rc6 and it seems to be working without issues.

**Comment by filmor** [comment]
So, what do you say? I could release tonight (European time), but I'd only have tomorrow morning to handle any potential issues. If that is fine with you, I'll do it, otherwise release will be on 2022-10-10.

**Comment by lostmsu** [comment]
Go for it @filmor
